### ISSUE TITLE
前端页面建议

### ISSUE THREAD

**Issue by yangchuansheng** [EYHN/hexo-tag-cplayer#1]
前端页面建议参考一下这个人的：https://github.com/ccbikai/musicplayer

下面是demo

![image](https://user-images.githubusercontent.com/15308462/30009497-7ea69a56-915b-11e7-94af-93745ca587fa.png)

**Comment by EYHN** [comment]
这个插件是为cplayer做的， 如果有任何界面上的建议，请到cplayer发issues。
